name: tus_client_dart
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 2.5.0
homepage: https://github.com/tomassasovsky/tus_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4
  http: ">=1.0.0 <2.0.0"
  speed_test_dart: ^1.0.5+0

dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.12
  test: ^1.25.8
